# -*- indent-tabs-mode: nil -*-
---

dependencies: []

galaxy_info:

  role_name: 'ejabberd'
  company: 'DebOps'
  author: 'Hartmut Goebel'
  description: 'Jabber/XMPP server'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Debian
      versions:
        - stretch

    - name: Ubuntu
      versions:
        - xenial
        - artful

  galaxy_tags:
    - ejabberd
    - jabber
    - xmpp
